# Generated by Django 3.2.6 on 2021-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bin_iin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
