# Generated by Django 3.2.6 on 2021-10-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210927_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Физическое лицо'), (2, 'Организация'), (3, 'Торговый представитель'), (4, 'Курьер')], null=True),
        ),
    ]
