# Generated by Django 3.2.6 on 2021-10-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_storage_region'),
        ('users', '0005_auto_20211018_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_sector',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Пивнушка'), (2, 'Магазин'), (3, 'Супермаркет')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.storage_region'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_price',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Розничный'), (2, 'Оптовый'), (3, 'Спец.цена')], null=True),
        ),
    ]
