# Generated by Django 3.2.6 on 2021-11-13 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211108_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='galleon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paymets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/default.jpg', upload_to=users.models.user_photos_dir),
        ),
    ]
