# Generated by Django 3.2.6 on 2021-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211113_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_plan',
            field=models.IntegerField(blank=True, default=24),
        ),
        migrations.AddField(
            model_name='user',
            name='show_plan_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
