# Generated by Django 3.2.6 on 2021-11-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211118_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.BigIntegerField(default=0),
        ),
    ]
