# Generated by Django 3.2.6 on 2021-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211208_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_hour_until',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='working_hour_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
