# Generated by Django 3.2.6 on 2021-12-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('users', '0013_auto_20211212_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.type_price'),
        ),
    ]
