# Generated by Django 3.2.6 on 2021-12-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('users', '0014_alter_company_type_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.type_price'),
        ),
        migrations.AddField(
            model_name='user',
            name='sector_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.order_sector'),
        ),
    ]
