# Generated by Django 3.2.6 on 2021-10-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage_region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
