# Generated by Django 3.2.6 on 2021-10-18 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_storage_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country'),
        ),
        migrations.CreateModel(
            name='Outlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default/default.png', upload_to=locations.models.outlet_logo_dir)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=12)),
                ('credit', models.CharField(max_length=300)),
                ('paymets', models.IntegerField(default=0)),
                ('galleon', models.BooleanField(default=True)),
                ('debt', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
            ],
        ),
    ]
