# Generated by Django 3.2.6 on 2021-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
