# Generated by Django 3.2.6 on 2021-10-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20211019_2156'),
        ('locations', '0008_alter_location_city'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.outlets'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Новый'), (2, 'В обработке'), (2, 'Доставлен')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Розничный'), (2, 'Оптовый')], null=True),
        ),
    ]
