# Generated by Django 3.2.6 on 2021-11-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_delivery',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Самовывоз'), (2, 'Доставка')], default=1, null=True),
        ),
    ]
