# Generated by Django 3.2.6 on 2021-11-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_type_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='outlet',
        ),
        migrations.AlterField(
            model_name='order',
            name='type_order',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Розничный'), (2, 'Оптовый')], default=1, null=True),
        ),
    ]
