# Generated by Django 3.2.6 on 2021-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20211113_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
