# Generated by Django 3.2.6 on 2021-11-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_payment',
            field=models.SmallIntegerField(choices=[(1, 'Оплата наличными'), (2, 'Картой Visa/MasterCard '), (3, 'Оплата в системе Kaspi.kz')], default=1),
        ),
    ]
