# Generated by Django 3.2.6 on 2021-11-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20211124_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='comments',
            new_name='comment',
        ),
    ]
