# Generated by Django 3.2.6 on 2021-12-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20211110_2328'),
        ('order', '0013_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.storage_region'),
        ),
    ]
